import { MetadataRoute } from 'next';

export const dynamic = 'force-static';

export default function sitemap(): MetadataRoute.Sitemap {
    return [
        {
            url: 'https://epsilon-technology.com/',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 1,
        },
        {
            url: 'https://epsilon-technology.com/it-services/',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.9,
        },
        {
            url: 'https://epsilon-technology.com/about/',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/services/mobile-app-development/',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.9,
        },
        {
            url: 'https://epsilon-technology.com/services/web-development/',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.9,
        },
        {
            url: 'https://epsilon-technology.com/services/ecommerce-development/',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.9,
        },
        {
            url: 'https://epsilon-technology.com/services/custom-software/',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.9,
        },
        {
            url: 'https://epsilon-technology.com/services/ui-ux-design/',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.9,
        },
        {
            url: 'https://epsilon-technology.com/services/maintenance-support/',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.9,
        },
        {
            url: 'https://epsilon-technology.com/digital-marketing-for-general-surgeons/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/digital-marketing-for-spine-specialists/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/digital-marketing-for-ayurvedic-doctors/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/digital-marketing-for-dermatologists/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/digital-marketing-for-surgeon-doctors/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/digital-marketing-for-pediatric-doctors/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/digital-marketing-for-gynecologist-doctors/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/digital-marketing-for-dental-doctors/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/digital-marketing-for-ivf-doctors/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/digital-marketing-for-orthopedic-doctors/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/digital-marketing-for-doctors-in-junagadh/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/digital-marketing-for-doctors/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/doctor-marketing-in-junagadh/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/doctor-marketing-in-rajkot/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/doctor-marketing-in-morbi/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/digital-marketing-in-junagadh/',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.9,
        },
        {
            url: 'https://epsilon-technology.com/blog/',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/blog/doctor-marketing-ideas-junagadh/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: 'https://epsilon-technology.com/blog/mobile-app-development-guide-2026/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.9,
        },
        {
            url: 'https://epsilon-technology.com/blog/top-affordable-app-developers-2026/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/blog/the-real-cost-of-custom-application-development-2026/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/blog/5-signs-you-need-professional-website-development-services/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/blog/mobile-app-creation-services-native-vs-cross-platform/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/blog/business-solutions-through-technology/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/blog/digital-transformation-guide/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/blog/ecommerce-growth-strategies-2026/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/blog/junagadh-police-bandobast-app-case-study/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/blog/web-app-development-trends-usa-2026/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/contacts/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/digital-marketing/',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.9,
        },
        {
            url: 'https://epsilon-technology.com/faqs/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://epsilon-technology.com/services/whatsapp-business-api/',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.9,
        },
    ];
}
